---
version: "3.1"

services:
  #*****************************************************************************************************************************************
  #**** Manager
  #*****************************************************************************************************************************************
  kali:
    image: kalilinux/kali-rolling:latest
    container_name: voldemort3
    tty: true

  #*****************************************************************************************************************************************
  #**** Indexers
  #*****************************************************************************************************************************************

  # prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${prowlerUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME_ZONE}
    volumes:
      - ${configs}/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  #*****************************************************************************************************************************************
  #**** Media Management Services                                                                                                       
  #*****************************************************************************************************************************************

  # radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${radarUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME_ZONE}
    volumes:
      - ${configs}/radarr-config:/config
      - ${data}:/data
    ports:
      - "7878:7878"
    logging:
      driver: json-file
    restart: unless-stopped

  # sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${sonarrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME_ZONE}
    volumes:
      - ${configs}/sonarr-config:/config
      - ${data}:/data
    ports:
      - "8989:8989"
    logging:
      driver: json-file
    restart: unless-stopped

  # lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${lidarrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/lidarr-config:/config
      - ${data}:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  # readarr
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${readarrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/readarr-config:/config
      - ${data}:/data
    ports:
      - "8787:8787"
    restart: unless-stopped

  #*****************************************************************************************************************************************
  #**** Media Servers                                                                                                       
  #*****************************************************************************************************************************************

  # audiobookshelf
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=${audiobookshelfUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    volumes:
      - ${configs}/audiobookshelf:/config
      - ${audiobooks}:/audiobooks
      - ${metadata}:/metadata
    ports:
      - "13378:80"
    restart: unless-stopped

  # overseerr
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${overseerrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/overseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
  
  # plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${plexUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - ${configs}/plex-config:/config
      - ${media}:/media
    ports:
      - "32400:32400"
    restart: unless-stopped
  
  # jellyfin
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${jellyfinUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/jellyfin-config:/config
      - ${media}:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  #*****************************************************************************************************************************************
  #**** Download Clients                                                                                                     
  #*****************************************************************************************************************************************
  # qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${qbittorrentUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
      - WEBUI_PORT=8080
    volumes:
      - ${configs}/qbittorrent-config:/config
      - ${torrents}:/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
