---
version: "3.1"

name: mediaserver

services:

  #*****************************************************************************************************************************************
  #**** Index Manager
  #*****************************************************************************************************************************************
  # prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=${prowlerUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  #*****************************************************************************************************************************************
  #**** Media Management Services                                                                                                       
  #*****************************************************************************************************************************************

  # radarr Movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${radarUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/radarr-config:/config
      - ${data}:${data}
    ports:
      - "7878:7878"
    logging:
      driver: json-file
    restart: unless-stopped

  # sonarr TV
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${sonarrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/sonarr-config:/config
      - ${data}:${data}
    ports:
      - "8989:8989"
    logging:
      driver: json-file
    restart: unless-stopped

  # lidarr Music
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${lidarrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/lidarr-config:/config
      - ${data}:${data}
    ports:
      - "8686:8686"
    restart: unless-stopped

  # readarr Books
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${readarrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/readarr-config:/config
      - ${data}:${data}
    ports:
      - "8787:8787"
    restart: unless-stopped

  #*****************************************************************************************************************************************
  #**** Media Servers                                                                                                       
  #*****************************************************************************************************************************************

  # audiobookshelf
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      - AUDIOBOOKSHELF_UID=${audiobookshelfUID}
      - AUDIOBOOKSHELF_GID=${PGID}
    volumes:
      - ${configs}/audiobookshelf:/config
      - ${audiobooks}:${audiobooks}
      - ${metadata}:/metadata
    ports:
      - "13378:80"
    restart: unless-stopped

  # overseerr
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${overseerrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/overseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped
  
  # plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${plexUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - ${configs}/plex-config:/config
      - ${media}:${media}
    network_mode: host
    restart: unless-stopped
  
  # jellyseerr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${jellyseerrUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/jellyseerr-config:/app/config
    ports:
      - "5056:5055"
    restart: unless-stopped

  # jellyfin
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${jellyfinUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
    volumes:
      - ${configs}/jellyfin-config:/config
      - ${media}:${media}
    ports:
      - "8096:8096"
    restart: unless-stopped

  #*****************************************************************************************************************************************
  #**** Download Clients                                                                                                     
  #*****************************************************************************************************************************************
  # qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${qbittorrentUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${timezone}
      - WEBUI_PORT=8080
    volumes:
      - ${configs}/qbittorrent-config:/config
      - ${torrents}:${torrents}:rw
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  #sabnzbd
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${sabnzbdUID}
      - PGID=${PGID}
      - TZ=${timezone}
    volumes:
      - /${configs}/sabnzbd-config:/config
      - ${usenet}:${usenet}:rw
    ports:
      - 8081:8080
    restart: unless-stopped